segments = [
  {
    "Copying": [
      "t t t t t",
      "e e e e e",
      "a a a a a",
      "n n n n n",
      "tea",
      "eat",
      "ate",
      "at",
      "ten",
      "net",
      "tan",
      "eat at ten",
      "ate at ten"
  	],
    "Sending": [
      "tea",
      "ten",
      "net",
      "eat at ten",
      "ate at ten"
    ]
  },
  {
    "Copying": [
      "t t t t t",
      "e e e e e",
      "a a a a a",
      "n n n n n",
      "o o o o o",
      "i i i i i",
      "s s s s s",
      "1 1 1 1 1",
      "4 4 4 4 4",
      "ten",
      "ton",
      "tin",
      "tie",
      "toe",
      "no",
      "not",
      "note",
      "it",
      "sos",
      "one",
      "on",
      "son",
      "notes",
      "stone",
      "noise",
      "1 note",
      "no noise",
      "tie it",
      "1 ton stone",
      "N1AS",
      "N4ON",
      "S41T",
      "NO1S",
      "AI1E",
      "IT4O",
      "EA1ON",
      "ES4IT"
    ],
    "Sending": [
      "stone",
      "tin",
      "tie",
      "no",
      "not",
      "it",
      "at",
      "N1AS",
      "N4ON",
      "S41T",
      "NO1S",
      "AI1E",
      "IT4O",
      "EA1ON",
      "ES4IT",
      "1 ton stone",
      "14 notes",
      "ten sons"
    ]
  },
  {
    "Copying": [
      "o o o o o",
      "i i i i i",
      "s s s s s",
      "r r r r r",
      "h h h h h",
      "d d d d d",
      "l l l l l",
      "2 2 2 2 2",
      "5 5 5 5 5",
      "all",
      "tell",
      "tall",
      "the",
      "rst",
      "hi",
      "hill",
      "hello",
      "hole",
      "load",
      "led",
      "late",
      "lid",
      "sea",
      "sell",
      "she",
      "her",
      "he",
      "hr",
      "DL1AT",
      "HH5H",
      "HS1TD",
      "ND2T",
      "NA4T",
      "142",
      "451",
      "1425",
      "a tall hill",
      "she is here",
      "he is late",
      "12 hills"
    ],
    "Sending": [
      "all",
      "tell",
      "the",
      "rst",
      "late",
      "she",
      "her",
      "DL1AT",
      "HH5H",
      "HS1TD",
      "ND2T",
      "NA4T",
      "142",
      "451",
      "1425",
      "she is hr",
      "he is late"
    ]
  },
  {
    "Copying": [
      "r r r r r",
      "h h h h h",
      "d d d d d",
      "l l l l l",
      "1 1 1 1 1",
      "4 4 4 4 4",
      "u u u u u",
      "c c c c c",
      "chat",
      "chair",
      "chin",
      "chart",
      "touch",
      "such",
      "cu",
      "ur",
      "sun",
      "usa",
      "hold",
      "told",
      "sail",
      "rail",
      "tail",
      "nail",
      "oil",
      "soil",
      "coil",
      "rain",
      "dr",
      "toll",
      "tall",
      "tell",
      "cell",
      "call",
      "NC5A",
      "NA2T",
      "CU1LL",
      "CO5NO",
      "NU4R",
      "CT1AC",
      "CE1NI",
      "4241",
      "1452",
      "tell all",
      "on the air",
      "hole in 1"
    ],
    "Sending": [
      "chat",
      "chin",
      "rain",
      "tall",
      "tell",
      "NC5A",
      "NA2T",
      "CU1LL",
      "CO5NO",
      "NU4R",
      "CT1AC",
      "CE1NI",
      "4241",
      "1452",
      "tell all",
      "on the air",
      "hole in 1"
    ]
  },
  {
    "Copying": [
      "u u u u u",
      "c c c c c",
      "2 2 2 2 2",
      "5 5 5 5 5",
      "m m m m m",
      "w w w w w",
      "3 3 3 3 3",
      "6 6 6 6 6",
      "? ? ? ? ?",
      "wait",
      "wall",
      "well",
      "will",
      "much",
      "such",
      "water",
      "when",
      "what",
      "watt",
      "date",
      "which",
      "two",
      "tower",
      "who",
      "where",
      "es",
      "was",
      "wish",
      "mat",
      "mtr",
      "mtrs",
      "him",
      "her",
      "his",
      "hw?",
      "W3AA",
      "N3AM",
      "DM5RA",
      "W6AM",
      "N2AT",
      "RW5L",
      "ON4UN",
      "335",
      "1432",
      "6122",
      "5 mtrs",
      "how is it?",
      "who are u?",
      "what date?"
    ],
    "Sending": [
      "wait",
      "well",
      "watts",
      "date",
      "W3AA",
      "N3AM",
      "DM5RA",
      "W6AM",
      "N2AT",
      "RW5L",
      "ON4UN",
      "335",
      "1432",
      "6122",
      "5 watts",
      "who is this?",
      "tower es ant"
    ]
  },
  {
    "Copying": [
      "m m m m m",
      "w w w w w",
      "3 3 3 3 3",
      "6 6 6 6 6",
      "f f f f f",
      "y y y y y",
      "u",
      "toy",
      "foot",
      "tooth",
      "root",
      "cute",
      "noise",
      "my",
      "may",
      "ton",
      "teeth",
      "feet",
      "yet",
      "they",
      "say",
      "why",
      "ur",
      "fair",
      "fare",
      "far",
      "hw?",
      "F5IN",
      "YO1AR",
      "HH5H",
      "NO3M",
      "AA3U",
      "S52R",
      "1512",
      "3316",
      "yes it is",
      "I say no",
      "she says yes",
      "hw was hamfair?"
    ],
    "Sending": [
      "cute",
      "said",
      "noise",
      "noisy",
      "him",
      "feet",
      "hw?",
      "F5IN",
      "YO1AR",
      "HH5H",
      "NO3M",
      "AA3U",
      "S52R",
      "1512",
      "3316",
      "she says yes",
      "he says no",
      "who is he?",
      "he is well",
      "my name is Hiro"
    ]
  },
  {
    "Copying": [
      "f f f f f",
      "y y y y y",
      "3 3 3 3 3",
      "6 6 6 6 6",
      "p p p p p",
      "g g g g g",
      "7 7 7 7 7",
      "9 9 9 9 9",
      "/ / / / /",
      "page",
      "paper",
      "gld",
      "gold",
      "George",
      "Geo",
      "Chas",
      "chase",
      "change",
      "pen",
      "pencil",
      "gain",
      "gas",
      "age",
      "yes",
      "yet",
      "G4AN/3",
      "N1AR/5",
      "W9UCA/9",
      "W3/PY2AA",
      "F6/N6AM",
      "2N2222",
      "7423",
      "14253679",
      "he is a pro",
      "she is cute",
      "my age is 19"
    ],
    "Sending": [
      "page",
      "George",
      "pen",
      "G4AN/3",
      "N1AR/5",
      "W9UCA/9",
      "W3/PY2AA",
      "F6/N6AM",
      "2N2222",
      "7423",
      "14253679",
      "go to hamfair",
      "read the page",
      "what page?",
      "page 15"
    ]
  },
  {
    "Copying": [
      "b b b b b",
      "v v v v v",
      "7 7 7 7 7",
      "9 9 9 9 9",
      "/ / / / /",
      "vote",
      "view",
      "wave",
      "save",
      "valve",
      "volt",
      "bad",
      "body",
      "born",
      "barney",
      "brad",
      "bed",
      "btr",
      "best",
      "bill",
      "bld",
      "blt",
      "bolt",
      "bulb",
      "BV2AA",
      "BA1RO",
      "WB2AE",
      "K6RB/4",
      "W2/VE1AR",
      "VE2/K2LE",
      "6146",
      "5514",
      "name is bob",
      "name is bill",
      "name is ted",
      "name is Vinnie",
      "ur rst is 559",
      "ur rst is 459"
    ],
    "Sending": [
      "vote",
      "bed",
      "best",
      "BV2AA",
      "BA1RO",
      "WB2AE",
      "K6RB/4",
      "W2/VE1AR",
      "VE2/W2LE",
      "6146",
      "5514",
      "name is bill",
      "name is art",
      "ur rst is 579",
      "ur rst is 449"
    ]
  },
  {
    "Copying": [
      "b b b b b",
      "v v v v v",
      "k k k k k",
      "j j j j j",
      "8 8 8 8 8",
      "0 0 0 0 0",
      "&lt;BT&gt; &lt;BT&gt; &lt;BT&gt; &lt;BT&gt; &lt;BT&gt;",
      "Jack",
      "Jay",
      "John",
      "Jim",
      "Jerry",
      "back",
      "rack",
      "tech",
      "reach",
      "each",
      "teach",
      "help",
      "high",
      "hill",
      "face",
      "far",
      "fear",
      "then",
      "there",
      "him",
      "her",
      "his",
      "hers",
      "them",
      "they",
      "their",
      "switch",
      "line",
      "ant",
      "dipole",
      "vert",
      "ohms",
      "home",
      "away",
      "test",
      "Asia",
      "Africa",
      "K1JD",
      "N1AR",
      "W2TT",
      "K2UMU",
      "N2NW",
      "VE3NE",
      "VA3KP",
      "K4BAI",
      "N5KO",
      "807",
      "3500Z",
      "4250A",
      "hw is he?",
      "name is joe",
      "name is john",
      "name is jim",
      "ur rst is 579",
      "ur rst is 339",
      "sri no cpy"
    ],
    "Sending": [
      "jack",
      "reach",
      "each",
      "fear",
      "his",
      "ant",
      "K1JD",
      "N1AR",
      "W2TT",
      "K2UMU",
      "N2NW",
      "VE3NE",
      "VA3KP",
      "K4BAI",
      "N5KO",
      "807",
      "3500Z",
      "4250A",
      "name is fred",
      "name is tom",
      "name is john",
      "name is bob",
      "ur rst is 549"
    ]
  },
  {
    "Copying": [
      "k k k k k",
      "j j j j j",
      "8 8 8 8 8",
      "0 0 0 0 0",
      "x x x x x",
      "q q q q q",
      "z z z z z",
      "&lt;BK&gt; &lt;BK&gt; &lt;BK&gt; &lt;BK&gt; &lt;BK&gt;",
      "wl",
      "ur",
      "ok",
      "hw?",
      "QRX",
      "rig",
      "wx",
      "ant",
      "pwr",
      "kw",
      "name",
      "nyc",
      "sf",
      "dallas",
      "dollar",
      "nr",
      "rst",
      "uk",
      "usa",
      "Tokyo",
      "paris",
      "London",
      "hamburg",
      "Sydney",
      "ZL2TT",
      "VK4OM",
      "JE1TRV",
      "BA1CW",
      "KH6LC",
      "AL2A",
      "AA3B",
      "8044",
      "7400",
      "73",
      "u hv qsb",
      "u hv qrm",
      "name?",
      "qth?",
      "qth is ny",
      "qth is paris",
      "pse qsy to 7054"
    ],
    "Sending": [
      "wl",
      "ur",
      "ok",
      "qrx",
      "rig",
      "wx",
      "ant",
      "pwr",
      "kw",
      "qrz",
      "qth",
      "qrs",
      "qro",
      "qrp",
      "ZL2TT",
      "VK4OM",
      "JE1TRV",
      "BA1CW",
      "KH6LC",
      "AL2A",
      "AA3B",
      "8044",
      "7400",
      "73",
      "ur rst is 579",
      "qth is nr Tokyo",
      "name is kazu",
      "ur rst is 559",
      "qth is yokohama",
      "name is hoz"
    ]
  },
  {
    "Copying": [
      "[your callsign] de JL1GEL ur rst 579 nr Tokyo name is aki hw? [your callsign] de JL1GEL K",
      "[your callsign] de JH8PHT ur rst is 5nn &lt;BT&gt; qth Sapporo Sapporo &lt;BT&gt; op is kazu kazu de JH8PHT K",
      "[your callsign] de JJ0RBX &lt;BT&gt; ur rst 569 569 nr nobeyama name is hoz &lt;BK&gt;",
    ],
    "Sending": [
      "JL1GEL de [your callsign] ur rst 57n in [your town/city] name is [your name] btu JL1GEL de [your callsign] k",
      "JH8PHT de [your callsign] &lt;BT&gt; ur rst 56n in [your town/city] &lt;BT&gt; name [your name] JH8PHT de [your callsign] k",
      "JJ0RBX de [your callsign] ur rst 45n wid QRN in [your town/city] &lt;BT&gt; name is [your name] JJ0RBX de [your callsign] &lt;BK&gt;",
    ]
  },
  {
    "Copying": [
      "[your callsign] de JL1GEL wx cldy temp 25 c &lt;BT&gt; rig runs 100 w to vert &lt;BT&gt; age is 54 so hw? [your callsign] de JL1GEL k",
      "[your callsign] de JH8PHT &lt;BT&gt; wx rain temp 18 c &lt;BT&gt; rig is k3 es ant is 4 el yagi age is 50 ok? De JH8PHT",
      "[your callsign] de JJ0RBX wx snow temp minus 7 c rig is IC 7700 pwr is kw es ant is dipole age is 46 hw? &lt;BK&gt;",
    ],
    "Sending": [
      "JL1GEL de [your callsign] wx sunny temp 27 c rig runs [your power] w to [your antenna] age is [your age] hw? JL1GEL de [your callsign] k",
      "JH8PHT de [your callsign] wx rain temp 18 c rig runs [your power] w to [your antenna] age is [your age] hw? JH8PHT de [your callsign] k",
      "JJ0RBX de [your callsign] wx overcast temp 5 c &lt;BT&gt; rig runs [your power] w to [your antenna] &lt;BT&gt; age is [your age] hw? JJ0RBX de [your callsign] k",
    ]
  },
  {
    "Copying": [
      "[your callsign] de JL1GEL tnx fer qso es hpe cu agn 73 &lt;SK&gt; [your callsign] de JL1GEL",
      "[your callsign] de JH8PHT tnx fer nice qso cul 73 &lt;SK&gt; [your callsign] de JH8PHT gn ee",
      "[your callsign] de JJ0RBX enjoyed qso &lt;AR&gt; [your callsign] de JJ0RBX ee",
    ],
    "Sending": [
      "JL1GEL de [your callsign] tu fer qso cu agn 73 &lt;SK&gt; JL1GEL de [your callsign]",
      "JH8PHT de [your callsign] tks nice qso es cul 73 &lt;SK&gt; JH8PHT de [your callsign] ee",
      "JJ0RBX de [your callsign] enjoyed qso also 73 &lt;AR&gt; JJ0RBX de [your callsign] cu ee",
    ]
  }
]