segments = [
  {
    "Copying": [
      "t t t t t",
      "e e e e e",
      "a a a a a",
      "n n n n n",
      "tea",
      "tee",
      "eat",
      "ate",
      "at",
      "tat",
      "teen",
      "neat",
      "ten",
      "net",
      "tan"
	],
    "Sending": [
      "tea",
      "ten",
      "net",
      "tee"
	]
  },
  {
    "Copying": [
      "t t t t t",
      "e e e e e",
      "a a a a a",
      "n n n n n",
      "o o o o o",
      "i i i i i",
      "s s s s s",
      "1 1 1 1 1",
      "4 4 4 4 4",
      "ten",
      "ton",
      "tin",
      "tie",
      "toe",
      "no",
      "not",
      "note",
      "it",
      "at",
      "one",
      "neat",
      "net",
      "nit",
      "toes",
      "stone",
      "tease",
      "noise",
      "N1AS",
      "N4ON",
      "S41T",
      "NO1S",
      "AI1E",
      "IT4O",
      "EA1ON",
      "ES4IT"
    ],
    "Sending": [
      "stone",
      "tin",
      "tie",
      "no",
      "not",
      "it",
      "at",
      "N1AS",
      "N4ON",
      "S41T",
      "NO1S",
      "AI1E",
      "IT4O",
      "EA1ON",
      "ES4IT"
    ]
  },
  {
    "Copying": [
      "o o o o o",
      "i i i i i",
      "s s s s s",
      "r r r r r",
      "h h h h h",
      "d d d d d",
      "l l l l l",
      "2 2 2 2 2",
      "5 5 5 5 5",
      "all",
      "tell",
      "tall",
      "deal",
      "the",
      "their",
      "doll",
      "dell",
      "hall",
      "hill",
      "hole",
      "load",
      "lead",
      "late",
      "later",
      "seal",
      "sell",
      "sole",
      "she",
      "shed",
      "her",
      "hear",
      "DL1AT",
      "HH5H",
      "HS1TD",
      "ND2T",
      "NA4T",
      "142",
      "451",
      "1425"
    ],
    "Sending": [
      "all",
      "tell",
      "the",
      "lead",
      "late",
      "she",
      "her",
      "DL1AT",
      "HH5H",
      "HS1TD",
      "ND2T",
      "NA4T",
      "142",
      "451",
      "1425"
    ]
  },
  {
    "Copying": [
      "r r r r r",
      "h h h h h",
      "d d d d d",
      "l l l l l",
      "1 1 1 1 1",
      "4 4 4 4 4",
      "u u u u u",
      "c c c c c",
      "chat",
      "chair",
      "chin",
      "chart",
      "ouch",
      "couch",
      "touch",
      "such",
      "teach",
      "reach",
      "sun",
      "son",
      "hold",
      "told",
      "sail",
      "rail",
      "tail",
      "nail",
      "oil",
      "soil",
      "toil",
      "coil",
      "rain",
      "cause",
      "sauce",
      "toss",
      "toll",
      "tall",
      "tell",
      "cell",
      "call",
      "NC5A",
      "NA2T",
      "CU1LL",
      "CO5NO",
      "NU4R",
      "CT1AC",
      "CE1NI",
      "4241",
      "1452"
    ],
    "Sending": [
      "chat",
      "chin",
      "teach",
      "sail",
      "rain",
      "tall",
      "tell",
      "NC5A",
      "NA2T",
      "CU1LL",
      "CO5NO",
      "NU4R",
      "CT1AC",
      "CE1NI",
      "4241",
      "1452"
    ]
  },
  {
    "Copying": [
      "u u u u u",
      "c c c c c",
      "2 2 2 2 2",
      "5 5 5 5 5",
      "m m m m m ",
      "w w w w w",
      "3 3 3 3 3",
      "6 6 6 6 6",
      "? ? ? ? ?",
      "wait",
      "wall",
      "well",
      "will",
      "mall",
      "mill",
      "chum",
      "mow",
      "much",
      "such",
      "water",
      "wet",
      "what",
      "dew",
      "date",
      "atom",
      "tow",
      "tower",
      "were",
      "where",
      "was",
      "wish",
      "wash",
      "mat",
      "matt",
      "mel",
      "him",
      "her",
      "his",
      "hw?",
      "W3AA",
      "N3AM",
      "DM5RA",
      "W6AM",
      "N2AT",
      "RW5L",
      "ON4UN",
      "335",
      "1432",
      "6122"
    ],
    "Sending": [
      "wait",
      "well",
      "mall",
      "mill",
      "wet",
      "date",
      "W3AA",
      "N3AM",
      "DM5RA",
      "W6AM",
      "N2AT",
      "RW5L",
      "ON4UN",
      "335",
      "1432",
      "6122"
    ]
  },
  {
    "Copying": [
      "m m m m m",
      "w w w w w",
      "3 3 3 3 3",
      "6 6 6 6 6",
      "f f f f f",
      "y y y y y",
      "you",
      "toy",
      "foot",
      "tooth",
      "root",
      "cute",
      "noise",
      "larry",
      "roy",
      "ton",
      "teeth",
      "feet",
      "yet",
      "they",
      "say",
      "ray",
      "hay",
      "your",
      "fair",
      "fare",
      "far",
      "fur",
      "furry",
      "hw?",
      "F5IN",
      "YO1AR",
      "HH5H",
      "NO3M",
      "AA3 U",
      "S52R",
      "1512",
      "3316"
	],
    "Sending": [
      "cute",
      "said",
      "raid",
      "stir",
      "him",
      "feet",
      "hw?",
      "F5IN",
      "YO1AR",
      "HH5H",
      "NO3M",
      "AA3 U",
      "S52R",
      "1512",
      "3316"
    ]
  },
  {
    "Copying": [
      "f f f f f",
      "y y y y y",
      "3 3 3 3 3",
      "6 6 6 6 6",
      "p p p p p",
      "g g g g g",
      "7 7 7 7 7",
      "9 9 9 9 9",
      "/ / / / /",
      "page",
      "paper",
      "pepper",
      "glad",
      "glare",
      "large",
      "ledge",
      "george",
      "geo",
      "chas",
      "chase",
      "change",
      "peg",
      "pug",
      "pig",
      "pen",
      "pencil",
      "pipe",
      "pit",
      "gain",
      "garage",
      "guard",
      "gas",
      "gus",
      "chug",
      "yes",
      "yet",
      "yonder",
      "coy",
      "G4AN/3",
      "N1AR/5",
      "K9UCA/9",
      "W3/PY2AA",
      "F6/N6AM",
      "2N2222",
      "7423",
      "14253679"
    ],
    "Sending": [
      "page",
      "glare",
      "ledge",
      "george",
      "pen",
      "pit",
      "G4AN/3",
      "N1AR/5",
      "K9UCA/9",
      "W3/PY2AA",
      "F6/N6AM",
      "2N2222",
      "7423",
      "14253679"
    ]
  },
  {
    "Copying": [
      "b b b b b",
      "v v v v v",
      "7 7 7 7 7",
      "9 9 9 9 9",
      "/ / / / /",
      "vote",
      "vat",
      "view",
      "wave",
      "pave",
      "save",
      "vow",
      "valve",
      "solve",
      "volt",
      "vault",
      "bad",
      "body",
      "bore",
      "born",
      "barn",
      "barney",
      "brad",
      "bread",
      "bed",
      "better",
      "best",
      "bill",
      "build",
      "built",
      "bolt",
      "bulb",
      "blame",
      "blend",
      "bland",
      "blow",
      "BV2AA",
      "BA1RO",
      "WB2AE",
      "N6RB/4",
      "W2/VE1AR",
      "VE2/K2LE",
      "6146",
      "5514"
    ],
    "Sending": [
      "vote",
      "valve",
      "bed",
      "best",
      "BV2AA",
      "BA1RO",
      "WB2AE",
      "N6RB/4",
      "W2/VE1AR",
      "VE2/K2LE",
      "6146",
      "5514"
    ]
  },
  {
    "Copying": [
      "b b b b b",
      "v v v v v",
      "k k k k k",
      "j j j j j",
      "8 8 8 8 8",
      "0 0 0 0 0",
      "&lt;BT&gt; &lt;BT&gt; &lt;BT&gt; &lt;BT&gt; &lt;BT&gt;",
      "jack",
      "jay",
      "john",
      "jim",
      "jerry",
      "back",
      "rack",
      "tack",
      "tech",
      "tach",
      "reach",
      "each",
      "teach",
      "help",
      "high",
      "hill",
      "fact",
      "face",
      "far",
      "fear",
      "then",
      "their",
      "him",
      "her",
      "his",
      "hers",
      "them",
      "they",
      "their",
      "switch",
      "line",
      "ant",
      "dipole",
      "vertical",
      "ohms",
      "home",
      "away",
      "test",
      "asia",
      "Africa",
      "K1JD",
      "N1AR",
      "W2TT",
      "K2UMU",
      "N2NW",
      "VE3NE",
      "VA3KP",
      "K4BAI",
      "N5KO",
      "807",
      "3500Z",
      "4250A"
    ],
    "Sending": [
      "jack",
      "tach",
      "reach",
      "each",
      "fear",
      "his",
      "ant",
      "K1JD",
      "N1AR",
      "W2TT",
      "K2UMU",
      "N2NW",
      "VE3NE",
      "VA3KP",
      "K4BAI",
      "N5KO",
      "807",
      "3500Z",
      "4250A"
    ]
  },
  {
    "Copying": [
      "k k k k k",
      "j j j j j",
      "8 8 8 8 8",
      "0 0 0 0 0",
      "x x x x x",
      "q q q q q",
      "z z z z z",
      "&lt;BK&gt; &lt;BK&gt; &lt;BK&gt; &lt;BK&gt; &lt;BK&gt;",
      "wl",
      "ur",
      "ok",
      "hw?",
      "qrx",
      "rig",
      "wx",
      "ant",
      "pwr",
      "kw",
      "name",
      "Memphis",
      "nyc",
      "sf",
      "dallas",
      "Houston",
      "nm",
      "nj",
      "ca",
      "ut",
      "al",
      "ar",
      "il",
      "in",
      "me",
      "ma",
      "ct",
      "co",
      "qrm",
      "ne",
      "sd",
      "nd",
      "pa",
      "ky",
      "fl",
      "nc",
      "sc",
      "sdgo",
      "lax",
      "la",
      "on",
      "sk",
      "mb",
      "nt",
      "ab",
      "qc",
      "nb",
      "ns",
      "nr",
      "rst",
      "uk",
      "usa",
      "Tokyo",
      "paris",
      "London",
      "hamburg",
      "Sydney",
      "ZL2TT",
      "VK4OM",
      "JE1TRV",
      "BA1CW",
      "KH6LC",
      "AL2A",
      "AA3B",
      "8044",
      "7400",
      "73"
    ],
    "Sending": [
      "wl",
      "ur",
      "ok",
      "qrx",
      "rig",
      "wx",
      "ant",
      "pwr",
      "kw",
      "qrz",
      "qth",
      "qrs",
      "qro",
      "qrp",
      "ZL2TT",
      "VK4OM",
      "JE1TRV",
      "BA1CW",
      "KH6LC",
      "AL2A",
      "AA3B",
      "8044",
      "7400",
      "73"
    ]
  },
  {
    "Copying": [
      "[your callsign] de k6rb ur rst 579 nr sf name rob hw? [your callsign] de k6rb k",
      "[your callsign] de n3jt ur rst is 5nn <BT> qth mclean va ? mclean va <BT> op is jim de n3jt",
      "[your callsign] de w1rm <BT> ur rst 569 569 in ct name is pete bk"
    ],
    "Sending": [
      "k6rb de [your callsign] - ur rst 57n in [your town/city and state abbreviation] - name is [your name] btu k6rb de [your callsign] k",
      "n3jt de [your callsign] - ur rst 56n in [your town/city and state abbreviation] - name is [your name] - n3jt de [your callsign] k",
      "w1rm de [your callsign] - ur rst 45n wid QRN in [your town/city and state abbreviation] - name is [your name] - w1rm de [your callsign] k"
    ]
  },
  {
    "Copying": [
      "[your callsign] de k6rb wx cldy temp 58 <BT> rig runs 100 w to vert <BT> age is 66 so hw? [your callsign] de k6rb k",
      "[your callsign] de n3jt <BT> wx rain temp 42 <BT> rig is k3 es ant is 4 el yagi - age is 65 ok? de n3jt",
      "[your callsign] de w1rm wx snow temp 24 rig is IC 7700 pwr is kw es ant is dipole age is 70 hw? BK"
    ],
    "Sending": [
      "k6rb de [your callsign] - wx sunny temp 82 - rig runs [your power] w to [your antenna] - age is [your age] hw? k6rb de [your callsign] k",
      "n3jt de [your callsign] - wx rain temp 54 -r ig runs [your power] w to [your antenna] - age is [your age] hw? n3jt de [your callsign] k",
      "w1rm de [your callsign] - wx oc temp 70 - rig runs [your power] w to [your antenna] - age is [your age] hw? w1rm de [your callsign] k"
    ]
  },
  {
    "Copying": [
      "[your callsign] de k6rb tnx fer qso es hpe cu agn 73 sk [your callsign] de k6rb ee",
      "[your callsign] de n3jt nice qso tnx cul 73 sk [your callsign] de n3jt gn",
      "[your callsign] de w1rm - enjoyed qso sk [your callsign] de w1rm ee"
    ],
    "Sending": [
      "k6rb de [your callsign] tu fer qso cu agn 73 sk k6rb de [your callsign]",
      "n3jt de [your callsign] cul es nice qso 73 sk k6rb de [your callsign] eeSegment: w1rm de [your callsign] enjoyed qso also 73 sk w1rm de [your callsign] cu ee"
    ]
  }
]